server:
  port: 8888
spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:./target/local_db;DB_CLOSE_DELAY=-1
    show-sql: true

# App Properties
ru:
  lanit:
    bpm:
      jedu:
        hrjedi:
          jwtExpiration: 3600000
