server:
  port: 8888
spring:
  datasource:
    username: postgres
    password: 1234567890
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/HR_JEDI_DEV
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        temp:
          use_jdbc_metadata_defaults: false

# App Properties
ru:
  lanit:
    bpm:
      jedu:
        hrjedi:
          jwtExpiration: 3600000
