# Spring
server:
  port: 8888
spring:
  datasource:
    url: jdbc:h2:./target/local_db;AUTO_SERVER=TRUE
    username: sa
    password:
  h2.console.enabled: true

# Camunda
camunda.bpm:
  admin-user:
    id: admin
    password: admin
    firstName: Administrator
    lastName: Camunda
  job-execution:
    enabled: true

# App Properties
ru:
  lanit:
    bpm:
      jedu:
        hrjedi:
          jwtExpiration: 3600

# logging
logging:
  level:
    ru.lanit: debug
#    org.springframework: debug
